--- #YAML:1.0
name:                Mac-CocoaDialog
version:             0.0.3
abstract:            script with CocoaDialog
license:             ~
author:              
    - Flavio Poletti <flavio [at] polettix [dot] it>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Exception:               0
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
