---
name: Mac-CocoaDialog
version: 0.0.2
author:
  - 'Flavio Poletti <flavio [at] polettix [dot] it>'
abstract: script with CocoaDialog
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::Exception: 0
  Test::More: 0
  version: 0
provides:
  Mac::CocoaDialog:
    file: lib/Mac/CocoaDialog.pm
    version: 0.0.2
  Mac::CocoaDialog::Runner:
    file: lib/Mac/CocoaDialog.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
